export const ActionTypes = {
  SET_LOADING: 'SET_LOADING',
  SET_COMMENTS_LOADING: 'SET_COMMENTS_LOADING',
  SET_POSTS: 'SET_POSTS',
  SET_USER_INFO: 'SET_USER_INFO',
  SET_USER_POSTS: 'SET_USER_POSTS',
  SET_COMMENTS: 'SET_COMMENTS',
  FETCH_POSTS: 'FETCH_POSTS',
  FETCH_USER_INFO: 'FETCH_USER_INFO',
  FETCH_USER_POSTS: 'FETCH_USER_POSTS',
  FETCH_COMMENTS: 'FETCH_COMMENTS',
};